### ISSUE TITLE
Assign project name for this project

### ISSUE THREAD

**Issue by Sharp0802** [HB312/STAC2023#5]
Although this project has been created on GitHub,
This project is unnamed and we cannot create projects and solution.
We need to decide name of project **immediately**.

**Comment by DevLapis** [comment]
how about "NewStyle"?

**Comment by Sharp0802** [comment]
How about "HelloWorld"?

**Comment by dev-ruby** [comment]
NewNews

**Comment by Sharp0802** [comment]
#6 : Discussion opened. Please vote in this discussion.

**Comment by Sharp0802** [comment]
#6 : Discussion closed. Our project name has been decided: `NewStyle`
